<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Suhas. P. K" />

<meta name="date" content="2025-10-12" />

<title>Analysis of FHIR packages based on the FHIR versions</title>

<script src="FHIR-packages-analysisV1_files/header-attrs-2.29/header-attrs.js"></script>
<script src="FHIR-packages-analysisV1_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<link href="FHIR-packages-analysisV1_files/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet" />
<script src="FHIR-packages-analysisV1_files/bootstrap-5.3.1/bootstrap.bundle.min.js"></script>
<script src="FHIR-packages-analysisV1_files/bs3compat-0.9.0/transition.js"></script>
<script src="FHIR-packages-analysisV1_files/bs3compat-0.9.0/tabs.js"></script>
<script src="FHIR-packages-analysisV1_files/bs3compat-0.9.0/bs3compat.js"></script>
<script src="FHIR-packages-analysisV1_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="FHIR-packages-analysisV1_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="FHIR-packages-analysisV1_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="FHIR-packages-analysisV1_files/navigation-1.1/tabsets.js"></script>
<link href="FHIR-packages-analysisV1_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="FHIR-packages-analysisV1_files/highlightjs-9.12.0/highlight.js"></script>
<script src="FHIR-packages-analysisV1_files/kePrint-0.0.1/kePrint.js"></script>
<link href="FHIR-packages-analysisV1_files/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Analysis of FHIR packages based on the FHIR
versions</h1>
<h4 class="author">Suhas. P. K</h4>
<h4 class="date">2025-10-12</h4>

</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The <strong>Fast Healthcare Interoperability Resources
(FHIR®)</strong> standard is the foundation for modern health data
exchange. With the growing number of implementation guides (IGs),
extensions, and reusable data artifacts published across the healthcare
ecosystem, understanding how these packages evolve is essential for data
quality, interoperability, and analytics readiness.</p>
<p>This project focuses on <strong>Exploratory Data Analysis
(EDA)</strong> of the FHIR Package Index - a comprehensive dataset of
published FHIR packages hosted at <a
href="https://packages2.fhir.org/xig">packages2.fhir.org/xig</a>. Each
package in this dataset represents a distinct FHIR resource collection,
containing metadata such as version, working group, publication date,
and development maturity level (FMM).</p>
<div id="objectives" class="section level2">
<h2>Objectives</h2>
<p>The primary goals of this analysis are to:</p>
<ul>
<li><p>Explore the structure and composition of FHIR packages across
different versions.</p></li>
<li><p>Identify publication trends - including the number of active
vs. draft packages and their distribution over time.</p></li>
<li><p>Assess maturity and adoption patterns using the FHIR Maturity
Model (FMM) levels.</p></li>
<li><p>Understand working group contributions and how they align with
key healthcare domains (clinical, administrative, financial).</p></li>
<li><p>Visualize the ecosystem to provide actionable insights for
interoperability stakeholders, developers, and data scientists.</p></li>
</ul>
<hr />
</div>
<div id="data-collection" class="section level2">
<h2>Data Collection</h2>
<p>The dataset used in this analysis was collected directly from the
FHIR Package Index hosted at <strong>packages2.fhir.org/xig</strong>, an
official registry maintained by HL7®. This index lists all publicly
available <strong>FHIR Implementation Guides (IGs)</strong> and
associated resource packages. Each entry in the index includes metadata
describing the package name, version, identity, publication status,
working group, FHIR maturity level (FMM), release date, realm, and
authorship.</p>
<p>To build the dataset, an automated <a
href="./fhir_pkg_data_collection.R">web-scraping script</a> was
developed in R using the <code>rvest</code>, <code>httr2</code>, and
<code>jsonlite</code> libraries. The script iteratively navigates
through the paginated web interface (200 entries per page), extracts
each package’s metadata, and compiles them into structured JSON and
NDJSON formats. This approach ensures that the data is comprehensive and
up to date with the latest package releases.</p>
<p>The final dataset contains over <strong>75,000 FHIR package
records</strong>, representing various <strong>FHIR versions</strong>
and working groups across multiple healthcare domains. These records
were then transformed into a dataframe within R for further exploration
and visualization. The collection process preserves transparency and
reproducibility, making the dataset suitable for large-scale analysis
and trend identification within the FHIR ecosystem.</p>
</div>
<div id="libraries" class="section level2">
<h2>Libraries</h2>
<pre class="r"><code># Data handling &amp; Manipulation
library(jsonlite)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(lubridate)

# Visualization
library(ggplot2)
library(ggdark)
library(scales)
library(viridis)

# EDA Utilities
library(skimr)
library(DataExplorer)
library(summarytools)

# Table Rendering &amp; Reporting
library(knitr)
library(kableExtra)
library(DT)</code></pre>
</div>
</div>
<div id="about-the-data" class="section level1">
<h1>About the Data</h1>
<pre class="r"><code># read full JSON array
data &lt;- fromJSON(&quot;xig_resources.json&quot;, flatten = TRUE)

# convert to dataframe
df &lt;- as.data.frame(data)

glimpse(df)</code></pre>
<pre><code>## Rows: 75,411
## Columns: 12
## $ package_text  &lt;chr&gt; &quot;hl7.fhir.uv.vulcan-schedule&quot;, &quot;smart.who.int.base&quot;, &quot;hl…
## $ package_href  &lt;chr&gt; &quot;https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/&quot;, &quot;ht…
## $ version       &lt;chr&gt; &quot;R4&quot;, &quot;R4&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R5&quot;, &quot;R…
## $ identity_text &lt;chr&gt; &quot;ActivityDefinition/H2Q-MC-LZZT-Vital-Signs-Temperature&quot;…
## $ identity_href &lt;chr&gt; &quot;/xig/resource/hl7.fhir.uv.vulcan-soa%7Ccurrent/Activity…
## $ name_title    &lt;chr&gt; &quot;Vital Signs - Temperature&quot;, &quot;SGDecisionTableGuidance&quot;, …
## $ status        &lt;chr&gt; &quot;active&quot;, &quot;draft&quot;, &quot;active&quot;, &quot;active&quot;, &quot;active&quot;, &quot;active…
## $ fmm           &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, …
## $ wg            &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, …
## $ date          &lt;chr&gt; &quot;2023-04&quot;, &quot;2025-06&quot;, &quot;2024-05&quot;, &quot;2024-05&quot;, &quot;2025-08&quot;, &quot;…
## $ realm         &lt;chr&gt; &quot;uv&quot;, &quot;&quot;, &quot;uv&quot;, &quot;uv&quot;, &quot;pl&quot;, &quot;pl&quot;, &quot;pl&quot;, &quot;pl&quot;, &quot;pl&quot;, &quot;pl&quot;…
## $ auth          &lt;chr&gt; &quot;hl7&quot;, &quot;who&quot;, &quot;hl7&quot;, &quot;hl7&quot;, &quot;hl7&quot;, &quot;hl7&quot;, &quot;hl7&quot;, &quot;hl7&quot;, …</code></pre>
<p>Using <code>skimr</code> to understand the data summary in a tabular
form</p>
<pre class="r"><code>skimmed &lt;- skim(df)

kable(
  skimmed,
  format = &quot;html&quot;,
  booktabs = TRUE
) %&gt;%
  kable_styling(
    full_width = FALSE,
    font_size = 12,
    bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;, &quot;responsive&quot;)
  ) %&gt;%
  scroll_box(width = &quot;100%&quot;, height = &quot;500px&quot;)</code></pre>
<div
style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:500px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-condensed table-responsive" style="font-size: 12px; color: black; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
skim_type
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
skim_variable
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
n_missing
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
complete_rate
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
character.min
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
character.max
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
character.empty
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
character.n_unique
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
character.whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
package_text
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1096
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
package_href
</td>
<td style="text-align:right;">
22423
</td>
<td style="text-align:right;">
0.7026561
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
601
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
version
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
identity_text
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
115
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
72073
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
identity_href
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
163
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
75271
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
name_title
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
261
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
66231
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
status
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
fmm
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
67991
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
wg
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
65241
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
date
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
10639
</td>
<td style="text-align:right;">
193
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
realm
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
22398
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
auth
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
25640
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
</div>
<div id="data-summary-highlights" class="section level3">
<h3>Data Summary Highlights</h3>
<p><strong>Total Variables</strong>: 11 (all character type)</p>
<p><strong>Total Records</strong>: ~75,000 FHIR package entries</p>
</div>
<div id="core-fields" class="section level3">
<h3>Core Fields</h3>
<ul>
<li><p><code>package_text</code> – Fully complete (no missing values);
contains 1,096 unique package names.</p></li>
<li><p><code>package_href</code> – About 30% missing (complete_rate =
0.70); 601 unique hyperlinks to package definitions.</p></li>
<li><p><code>version</code> – Consistently present with 5 unique values
(likely representing FHIR versions like R2–R5).</p></li>
<li><p><code>identity_text</code> / <code>identity_href</code> – Both
complete and unique for almost every record (over 70k unique
identifiers).</p></li>
</ul>
</div>
<div id="descriptive-metadata" class="section level3">
<h3>Descriptive Metadata</h3>
<ul>
<li><p><code>name_title</code> – Fully populated, contains descriptive
names or titles (up to 261 characters); 66k unique entries.</p></li>
<li><p><code>status</code> – 9 unique values (e.g., active, draft,
retired), with full completeness across records.</p></li>
<li><p><code>fmm</code> (FHIR Maturity Model) – Mostly empty (~90%
blank); only 7 unique maturity levels recorded.</p></li>
<li><p><code>wg</code> (Working Group) – Sparse data; 30 unique working
groups identified, but ~65k empty values.</p></li>
<li><p><code>date</code> – Present for all records, with 193 unique date
entries (likely publication dates).</p></li>
<li><p><code>realm</code> – Optional metadata; 39 unique realms (e.g.,
US, AU, UK), ~22k missing.</p></li>
<li><p><code>auth</code> – Author or organization field, lightly
populated (only 5 unique values).</p></li>
</ul>
</div>
<div id="overall-data-quality" class="section level3">
<h3>Overall Data Quality</h3>
<ul>
<li><p>Core technical identifiers (<code>identity_text</code>,
<code>identity_href</code>) are strong and unique.</p></li>
<li><p>Descriptive and governance fields (<code>wg</code>,
<code>fmm</code>, <code>realm</code>, <code>auth</code>) have high
sparsity.</p></li>
<li><p>Excellent completeness for essential attributes
(<code>name</code>, <code>version</code>, <code>status</code>).</p></li>
<li><p>Text length variability indicates diverse and detailed metadata
descriptions.</p></li>
</ul>
</div>
<div id="data-quality-assessment" class="section level3">
<h3>Data Quality Assessment</h3>
<p>The FHIR package dataset demonstrates a generally strong structural
quality, with all <strong>11 variables</strong> consistently defined and
fully aligned across nearly 75,000 records. Core technical fields such
as <code>identity_text</code>, <code>identity_href</code>,
<code>package_text</code>, and <code>version</code> show excellent
completeness and uniqueness, ensuring reliable identification of each
FHIR package. These attributes form the backbone of the dataset and can
be confidently used for trend, frequency, and relationship analyses.</p>
<p>However, several descriptive and governance-related attributes -
notably <code>fmm</code>, <code>wg</code>, <code>realm</code>, and
<code>auth</code> - exhibit significant sparsity. The FHIR Maturity
Model (<code>fmm</code>) field is largely missing, limiting the ability
to analyze maturity progression across resources. Similarly,
<code>wg</code> (Working Group) and realm values are incomplete for many
packages, suggesting gaps in metadata publication or inconsistencies in
source documentation.</p>
<p>Textual attributes such as <code>name_title</code> and
<code>status</code> are well-populated and diverse, offering good
analytical potential for classification and pattern exploration.
Overall, while the dataset provides robust coverage for technical and
structural aspects, additional enrichment or cross-referencing may be
necessary for deeper organizational or maturity-related analyses. This
quality profile makes the dataset ideal for exploratory visualization,
version distribution analysis, and metadata completeness assessment
across the FHIR ecosystem.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
